[package]
name = "rime-dng"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bytemuck.workspace = true
gamut-dng = "=1.0.0"
gamut-ifd = { version = "=2.0.1", features = ["bigtiff"] }
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]

[lints]
workspace = true
